version: '3.7'

services:
   mock-server:
      image: mockserver/mockserver
      ports:
        - "1080:1080"
      environment:
        MOCKSERVER_SERVER_PORT: 1080
        MOCKSERVER_LOG_LEVEL: TRACE

   go-gin:
      build: ./go_gin
      ports:
        - "8081:8080"

   spring_cloud:
      build: ./spring_cloud_gw
      ports:
        - "8082:8080"

